-- Banco de Dados - App da Foto

CREATE DATABASE APPDAFOTO
GO

USE APPDAFOTO
GO

CREATE TABLE FOTOGRAFO (
IDFOTOGRAFO INT IDENTITY PRIMARY KEY,
NOME VARCHAR(45) NOT NULL,
ESPECIALIDADE VARCHAR(20) NOT NULL,
SEXO CHAR(1) NOT NULL CHECK (SEXO IN('M','F')),
NASCIMENTO DATE NOT NULL,
EMAIL VARCHAR(45) NOT NULL UNIQUE,
SENHA VARCHAR(30) NOT NULL,
CADASTRO DATETIME NOT NULL
)

CREATE TABLE ENDERECO (
IDENDERECO INT IDENTITY PRIMARY KEY,
LOGRADOURO VARCHAR(45) NOT NULL,
NUMERO VARCHAR(6) NOT NULL,
COMPLEMENTO VARCHAR(55),
BAIRRO VARCHAR(30) NOT NULL,
CIDADE VARCHAR(30) NOT NULL,
ESTADO CHAR(2) NOT NULL,
CEP CHAR(8) NOT NULL,
ID_FOTOGRAFO INT UNIQUE
)

CREATE TABLE CONTATO (
IDCONTATO INT IDENTITY PRIMARY KEY,
TELEFONE VARCHAR(11) NOT NULL,
TIPOTELEFONE CHAR(3) NOT NULL CHECK (TIPOTELEFONE IN('CEL','COM','RES')),
INSTAGRAM VARCHAR(60),
ACESSOSINSTAGRAM INT,
ID_FOTOGRAFO INT UNIQUE
)

CREATE TABLE FOTO (
IDFOTO INT IDENTITY PRIMARY KEY,
NOMEARQUIVO VARCHAR(50) NOT NULL,
IMAGEM VARBINARY(MAX) NOT NULL,
MIME VARCHAR(50) NOT NULL,
HORAUPLOAD DATETIME,
PERFIL CHAR(1) NOT NULL,
ID_FOTOGRAFO INT
)

ALTER TABLE ENDERECO ADD CONSTRAINT FK_ENDERECO_FOTOGRAFO
FOREIGN KEY(ID_FOTOGRAFO) REFERENCES FOTOGRAFO(IDFOTOGRAFO)

ALTER TABLE CONTATO ADD CONSTRAINT FK_CONTATO_FOTOGRAFO
FOREIGN KEY(ID_FOTOGRAFO) REFERENCES FOTOGRAFO(IDFOTOGRAFO)

ALTER TABLE FOTO ADD CONSTRAINT FK_FOTO_FOTOGRAFO
FOREIGN KEY(ID_FOTOGRAFO) REFERENCES FOTOGRAFO(IDFOTOGRAFO)


SELECT NOME, ESPECIALIDADE FROM FOTOGRAFO

SELECT IDFOTOGRAFO, NOME, ESPECIALIDADE FROM FOTOGRAFO WHERE = IDFOTOGRAFO

USE APPDAFOTO
GO

ALTER TABLE [dbo].[FOTOGRAFO] ADD CONSTRAINT GT_CADASTRO
DEFAULT GETDATE() FOR CADASTRO
GO

USE APPDAFOTO
GO

ALTER TABLE FOTOGRAFO 
DEFAULT GETDATE() FOR CADASTRO
GO

